sudo: false
language: node_js
node_js:
  - '4'
  - 'stable'

install:
  - npm install

script:
  - npm test
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      ./node_modules/sw-testing-helpers/project/publish-docs.sh master;
    fi
